blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<year>[0-9]{4})/(?P<slug>[\w\-]+)/', views.blog, name='article'),
    url(r'^archive/(?P<year>[0-9]{4})/', views.archive, name='archive'),
    url(r'^tag/(?P<tag_name>[\w]+)/', views.tag, name='tag'),
]

websiti/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', include('staticpage.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^blog/', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.utils.text import slugify
#from django.utils import timezone
import hashlib
import datetime
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Tag(models.Model):
    """Tags (e.g. gaming, linux). """
    name = models.CharField('Name', max_length=100, unique=True, help_text='Tag name, e.g. programming, linux.')
    created_at = models.DateTimeField('Created at', auto_now_add=True)

    def __str__(self):
        return self.name

class Article(models.Model):
    """The article / blog post model. """
    uuid = models.CharField(max_length=56, unique=True, null=True, editable=False)
    title = models.CharField('Title', max_length=150, unique=True)
    slug = models.SlugField(max_length=150, unique=True, help_text='Automatically generated.')
    description = models.TextField(max_length=500)
    content = RichTextUploadingField()
    tag = models.ManyToManyField(Tag, blank=True)
    publish = models.BooleanField('Publish?', default=True)
    created_at = models.DateTimeField('Created at', auto_now_add=True)
    modified_at = models.DateTimeField('Modified at', auto_now=True)
    views = models.IntegerField(default=0)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:article', kwargs={'year': self.created_at.year, 'slug': self.slug})

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model), args=(self.id,))

blog/views.py
from __future__ import unicode_literals

import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from blog.models import Tag, Article

# Create your views here.
def home(request):
    request.session['current_page'] = 'blog'
    tag_list = Tag.objects.filter(article__gt=0, article__publish=True).distinct().order_by('name')
    article_list = Article.objects.exclude(publish=False).order_by('-created_at')
    paginator = Paginator(article_list, 10, 3)

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # Page number is not int, return first page
        articles = paginator.page(1)
    except EmptyPage:
        # Page num out of range, return last page
        articles = paginator.page(paginator.num_pages)

    context = {'tags': tag_list, 'articles': articles, 'page_title': 'Blog'}
    response = render(request, 'blog/index.html', context)
    return response

def blog(request, year, slug):
    request.session['current_page'] = 'blog'
    from django.conf import settings
    article = get_object_or_404(Article, created_at__year=int(year), slug=str(slug), publish=True)
    recent_articles = Article.objects.exclude(pk=article.pk).exclude(publish=False).order_by('-views', '-created_at')[:10]

    context = {'article': article, 'recent_articles': recent_articles, 'show_comments': not settings.DEBUG}
    response = render(request, 'blog/view_article.html', context)

    # Page view counter cookies
    if request.COOKIES.get("view_%s" % str(article.uuid)) is None and not request.user.is_authenticated:
        response.set_cookie("view_%s" % str(article.uuid), value=str(article.title), expires=(datetime.datetime.now()+datetime.timedelta(days=2)))
        article.views += 1
        article.save()

    return response

def archive(request):
    # TODO
    return HttpResponse('todo')

def tag(request, tag_name):
    request.session['current_page'] = 'blog'
    article_list = get_list_or_404(Article, tag__name=str(tag_name), publish=True)
    tag_list = Tag.objects.filter(article__gt=0).distinct().order_by('name')

    paginator = Paginator(article_list, 10, 3)

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # Page number is not int, return first page
        articles = paginator.page(1)
    except EmptyPage:
        # Page num out of range, return last page
        articles = paginator.page(paginator.num_pages)

    context = {'articles': articles, 'tags': tag_list, 'page_title': "Tag: '%s'" % tag_name}
    response = render(request, 'blog/index.html', context)
    return response

templates/blog/base.html
{% load staticfiles %}

templates/blog/index.html
{% load staticfiles %}
<div class="container-fluid body">
     <div class="site-title">
         <h1>The road so far.</h1>
         <p>Hi, I'm an amateurcrastinator (not to be confused with procrastinator). <i>I'll explain later</i></p>
     </div>

     <div class="row">
         <div class="col-md-8">
             {% for article in articles %}
                 <div class="container article-card">
                     <article id="art-{{article.id}}">
                         <header>
                             <h2><a href="{{article.get_absolute_url}}">{{article.title}}</a></h2>
                         </header>
                         <section class="description">
                             <p>{{article.description}}</p>
                         </section>
                         <footer>
                             <span class="article-detail">
                                 <img src="{% static 'blog/image/calendar-2x.png' %}">
                                 <small>{{article.created_at|date:'d M Y'}} </small>
                                 <img src="{% static 'blog/image/clock-2x.png' %}">
                                 <small>{{article.created_at|date:'H:i'}} </small>
                                 <img src="{% static 'blog/image/eye-2x.png' %}">
                                 <small>{{article.views}}</small>
                             </span>
                         </footer>
                     </article>
                 </div>
             {% endfor %}

             <div class="pagination">
                 <span class="step-links">
                     {% if articles.has_previous %}
                         <a href="?page={{articles.previous_page_number}}">Newer posts</a>
                     {% endif %}

                     <span class="current">
                         Page {{articles.number}} of {{articles.paginator.num_pages}}
                     </span>

                     {% if articles.has_next %}
                         <a href="?page={{articles.next_page_number}}">Older posts</a>
                     {% endif %}
                 </span>
             </div>
         </div>

         <div class="col-md-4">
             {% if user.is_authenticated %}
             <div>
                 Welcome, {{user.username}}<br>
                 <a href="{% url 'admin:blog_article_add' %}" class="btn btn-primary btn-sm" role="button">Post new article</a>
             </div>
             {% endif %}
             <div class="tag-list">
                 <p>Tags:</p>
                 {% for tag in tags %}
                     <span><a href="{% url 'blog:tag' tag_name=tag.name %}" class="btn btn-light btn-sm" role="button"><small>{{tag.name}}</small></a></span>
                 {% endfor %}
             </div>
         </div>
     </div>

</div>

templates/blog/view_article.html
{% load staticfiles %}
<header>
    <h1>{{article.title}}</h1>
</header>
<section class="main-content">
    <div class="article-body">
        {{article.content|safe}}
    </div>
</section>